In [1]:
import numpy as np

In [4]:
np.random.seed(17)
A=np.random.randint(0,10,size=(5,5))
print("Matrix A\n",A)

Matrix A
 [[1 6 6 9 0]
 [6 4 7 4 7]
 [1 1 9 8 2]
 [3 6 6 9 9]
 [1 5 1 0 5]]


In [7]:
def row_echelon_form(matrix):
    A = matrix.copy()
    num_rows, num_cols = A.shape
    leading_col = 0  

    for r in range(num_rows):
        if leading_col >= num_cols:
            break
        
        pivot_row = r
        while pivot_row < num_rows and A[pivot_row, leading_col] == 0:
            pivot_row += 1
        
        if pivot_row < num_rows:
           
            A[[pivot_row, r]] = A[[r, pivot_row]]
            A[r] = A[r] / A[r, leading_col]
            for i in range(r + 1, num_rows):
                A[i] = A[i] - A[i, leading_col] * A[r]
        
        leading_col += 1
    
    return A
B=row_echelon_form(A)
print("Row Echelon Form of matrix\n",B)

Row Echelon Form of matrix
 [[1 6 6 9 0]
 [0 1 0 1 0]
 [0 0 1 1 0]
 [0 0 0 1 1]
 [0 0 0 0 1]]
